### ISSUE TITLE
.net core 2.0 compatibility? 

### ISSUE THREAD

**Issue by winkmichael** [garysharp/SmazSharp#1]
Any chance you will update this lib to work with .net Core 2.x?

**Comment by garysharp** [comment]
Don't see why not. Can you identify the incompatibilities? Happy to accept contributions :)

**Comment by winkmichael** [comment]
<img width="615" alt="screen shot 2018-06-21 at 8 49 13 pm" src="https://user-images.githubusercontent.com/5185889/41755437-a10a5592-7594-11e8-8f28-c84f2de5b2ae.png">

**Comment by winkmichael** [comment]
No matter the effort I can't get it to reference the NuGet package when using .NET 2.0

**Comment by garysharp** [comment]
It looks to me like the screenshot you submitted contains a syntax error. There is no such type as `SmazSharpbyte` and you need to pass in an input string, not declare one. It looks like you've just copied the method descriptor from the [readme](https://github.com/garysharp/SmazSharp/blob/master/README.md) file. The function is used the same way as any call to a c# function. For example:

```csharp
var compressedBytes = SmazSharp.Smaz.Compress("My String");
```

or

```csharp
string myInput = "My String";
byte[] myInputCompressed = SmazSharp.Smaz.Compress(myInput);
```

The underlining of `SmazSharp.Smaz` in your screenshot indicates the library isn't referenced in your project.

I created a new blank .NET Core 2.0 console application and was able to add the nuget reference and use the library with no issues. There was a warning speaking of _possible_ incompatibility - but it seemed to work in my initial test:

![image](https://user-images.githubusercontent.com/1687386/41763994-205f6c02-7643-11e8-8755-9fd2937fb5e6.png)

Any chance you could send through the steps you used so that I can reproduce the error?

**Comment by winkmichael** [comment]
Sorry I am a dummy. I managed to fix the typo in your readme when I tried with .net 4.5 but instantly assumed it was a .net core issue when I tried using it a .net core app. Thanks and sorry about that.
<img width="729" alt="screen shot 2018-06-22 at 7 18 03 am" src="https://user-images.githubusercontent.com/5185889/41778628-8a405e08-75ec-11e8-99a0-6f3b7c4fe200.png">

**Comment by garysharp** [comment]
I'm not seeing any typo in the readme file. Just the method descriptors (in a similar format to standard documentation - [for example](https://docs.microsoft.com/en-au/dotnet/api/system.string.indexof?view=netframework-4.7.2#System_String_IndexOf_System_String_System_Int32_)).
If you could let me know what needs to be changed in the readme I would appreciate it; better yet, submit a pull request.

**Comment by winkmichael** [comment]
Like I say I am a big dummy and instantly assumed it was .net core, I quickly copied and pasted - the equals is missing... 

byte[] SmazSharp.Smaz.Compress(string Input);

vs

byte[] VariableName = SmazSharp.Smaz.Compress(string Input);
